# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui',
# licensing of 'main.ui' applies.
#
# Created: Tue Apr  6 17:57:03 2021
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(595, 492)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Load1 = QtWidgets.QPushButton(self.centralwidget)
        self.Load1.setGeometry(QtCore.QRect(20, 250, 261, 31))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        self.Load1.setFont(font)
        self.Load1.setObjectName("Load1")
        self.Predict = QtWidgets.QPushButton(self.centralwidget)
        self.Predict.setGeometry(QtCore.QRect(20, 300, 261, 31))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        self.Predict.setFont(font)
        self.Predict.setAutoRepeatDelay(300)
        self.Predict.setObjectName("Predict")
        self.Load2 = QtWidgets.QPushButton(self.centralwidget)
        self.Load2.setGeometry(QtCore.QRect(310, 250, 261, 31))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(16)
        self.Load2.setFont(font)
        self.Load2.setObjectName("Load2")
        self.Bujae = QtWidgets.QLabel(self.centralwidget)
        self.Bujae.setGeometry(QtCore.QRect(100, 10, 111, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.Bujae.setFont(font)
        self.Bujae.setObjectName("Bujae")
        self.Gujo = QtWidgets.QLabel(self.centralwidget)
        self.Gujo.setGeometry(QtCore.QRect(390, 10, 131, 20))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.Gujo.setFont(font)
        self.Gujo.setObjectName("Gujo")
        self.graphicsView1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView1.setGeometry(QtCore.QRect(20, 40, 261, 192))
        self.graphicsView1.setObjectName("graphicsView1")
        self.Display1 = QtWidgets.QLabel(self.centralwidget)
        self.Display1.setGeometry(QtCore.QRect(20, 40, 261, 192))
        self.Display1.setText("")
        self.Display1.setObjectName("Display1")
        self.graphicsView2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView2.setGeometry(QtCore.QRect(310, 40, 261, 192))
        self.graphicsView2.setObjectName("graphicsView2")
        self.Display2 = QtWidgets.QLabel(self.centralwidget)
        self.Display2.setGeometry(QtCore.QRect(310, 40, 261, 192))
        self.Display2.setText("")
        self.Display2.setObjectName("Display2")
        self.Tin = QtWidgets.QPushButton(self.centralwidget)
        self.Tin.setGeometry(QtCore.QRect(19, 340, 261, 121))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        self.Tin.setFont(font)
        self.Tin.setText("")
        self.Tin.setIconSize(QtCore.QSize(261, 91))
        self.Tin.setObjectName("Tin")
        self.CAILAB = QtWidgets.QLabel(self.centralwidget)
        self.CAILAB.setGeometry(QtCore.QRect(310, 380, 261, 81))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.CAILAB.setFont(font)
        self.CAILAB.setText("")
        self.CAILAB.setObjectName("CAILAB")
        self.Launch_PLC = QtWidgets.QPushButton(self.centralwidget)
        self.Launch_PLC.setGeometry(QtCore.QRect(310, 300, 261, 31))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        self.Launch_PLC.setFont(font)
        self.Launch_PLC.setAutoRepeatDelay(300)
        self.Launch_PLC.setObjectName("Launch_PLC")
        self.PN = QtWidgets.QLabel(self.centralwidget)
        self.PN.setGeometry(QtCore.QRect(310, 340, 141, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.PN.setFont(font)
        self.PN.setObjectName("PN")
        self.PortNumber = QtWidgets.QSpinBox(self.centralwidget)
        self.PortNumber.setGeometry(QtCore.QRect(460, 340, 111, 31))
        self.PortNumber.setObjectName("PortNumber")
        self.Tin_Logo = QtWidgets.QLabel(self.centralwidget)
        self.Tin_Logo.setGeometry(QtCore.QRect(150, 390, 16, 16))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.Tin_Logo.setFont(font)
        self.Tin_Logo.setText("")
        self.Tin_Logo.setObjectName("Tin_Logo")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "T-in RIB_Automation", None, -1))
        self.Load1.setText(QtWidgets.QApplication.translate("MainWindow", "Load", None, -1))
        self.Predict.setText(QtWidgets.QApplication.translate("MainWindow", "Predict", None, -1))
        self.Load2.setText(QtWidgets.QApplication.translate("MainWindow", "Load", None, -1))
        self.Bujae.setText(QtWidgets.QApplication.translate("MainWindow", "부재리스트", None, -1))
        self.Gujo.setText(QtWidgets.QApplication.translate("MainWindow", "구조평면도", None, -1))
        self.Launch_PLC.setText(QtWidgets.QApplication.translate("MainWindow", "Transport Data to PLC", None, -1))
        self.PN.setText(QtWidgets.QApplication.translate("MainWindow", "Port Number", None, -1))
