# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui',
# licensing of 'main.ui' applies.
#
# Created: Mon Mar  8 11:05:34 2021
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(589, 486)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Load1 = QtWidgets.QPushButton(self.centralwidget)
        self.Load1.setGeometry(QtCore.QRect(20, 250, 261, 31))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        self.Load1.setFont(font)
        self.Load1.setObjectName("Load1")
        self.Predict = QtWidgets.QPushButton(self.centralwidget)
        self.Predict.setGeometry(QtCore.QRect(310, 300, 261, 31))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        self.Predict.setFont(font)
        self.Predict.setAutoRepeatDelay(300)
        self.Predict.setObjectName("Predict")
        self.Load2 = QtWidgets.QPushButton(self.centralwidget)
        self.Load2.setGeometry(QtCore.QRect(310, 250, 261, 31))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(16)
        self.Load2.setFont(font)
        self.Load2.setObjectName("Load2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 10, 111, 21))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(390, 10, 131, 20))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.graphicsView1 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView1.setGeometry(QtCore.QRect(20, 40, 261, 192))
        self.graphicsView1.setObjectName("graphicsView1")
        self.Display1 = QtWidgets.QLabel(self.centralwidget)
        self.Display1.setGeometry(QtCore.QRect(20, 40, 261, 192))
        self.Display1.setText("")
        self.Display1.setObjectName("Display1")
        self.graphicsView2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView2.setGeometry(QtCore.QRect(310, 40, 261, 192))
        self.graphicsView2.setObjectName("graphicsView2")
        self.Display2 = QtWidgets.QLabel(self.centralwidget)
        self.Display2.setGeometry(QtCore.QRect(310, 40, 261, 192))
        self.Display2.setText("")
        self.Display2.setObjectName("Display2")
        self.Tin = QtWidgets.QPushButton(self.centralwidget)
        self.Tin.setGeometry(QtCore.QRect(20, 300, 261, 161))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(16)
        font.setWeight(50)
        font.setBold(False)
        self.Tin.setFont(font)
        self.Tin.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("T_in_Robotics.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Tin.setIcon(icon)
        self.Tin.setIconSize(QtCore.QSize(261, 91))
        self.Tin.setObjectName("Tin")
        self.CAILAB = QtWidgets.QLabel(self.centralwidget)
        self.CAILAB.setGeometry(QtCore.QRect(310, 340, 261, 121))
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(16)
        font.setWeight(75)
        font.setBold(True)
        self.CAILAB.setFont(font)
        self.CAILAB.setText("")
        self.CAILAB.setObjectName("CAILAB")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "T-in RIB_Automation", None, -1))
        self.Load1.setText(QtWidgets.QApplication.translate("MainWindow", "Load", None, -1))
        self.Predict.setText(QtWidgets.QApplication.translate("MainWindow", "Predict", None, -1))
        self.Load2.setText(QtWidgets.QApplication.translate("MainWindow", "Load", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "부재리스트", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "구조평면도", None, -1))

